{{- if and .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "postgresql-operator.fullname" . }}-rolebinding
roleRef:
  kind: ClusterRole
  name: {{ include "postgresql-operator.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "postgresql-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
