apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-operator.fullname" . }}
  labels:
    {{- include "postgresql-operator.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: {{ include "postgresql-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
